name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache Android SDK and apt packages
        uses: actions/cache@v4
        with:
          path: |
            /home/runner/android-sdk
            /var/cache/apt/archives
            /var/lib/apt/lists
          key: ${{ runner.os }}-android-sdk-cache-${{ hashFiles('**/setup-android-sdk.sh') }}
          restore-keys: ${{ runner.os }}-android-sdk-cache-
      - name: Set execute permission for script
        run: chmod +x setup-android-sdk.sh
      - name: Install Android SDK
        run: |
          sudo ./setup-android-sdk.sh
          source $HOME/.profile
      - name: Set up environment variables
        run: |
          echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
          echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$HOME/android-sdk/platform-tools" >> $GITHUB_PATH
      - name: Build, Test and Lint
        run: |
          ./gradlew clean assemble test lintDebug
      - name: Dependency check
        run: ./gradlew dependencyCheckAnalyze
      - name: Run instrumented tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 35
          script: ./gradlew connectedAndroidTest
