name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Android SDK
        run: |
          bash setup-android-sdk.sh
          source $HOME/.profile
      - name: Build, Test and Lint
        run: |
          ./gradlew clean assemble test lintDebug
      - name: Run instrumented tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 34
          script: ./gradlew connectedAndroidTest
